### ISSUE TITLE
Support CCXT broker

### ISSUE THREAD

**Issue by Industrial** [zipline-live/zipline#120]
Hi!

Currently, zipline-live only supports Interactive Brokers. With CCXT it would add support for all of crypto-land.

gr,

Tom

**Comment by cal97g** [comment]
CCXT isn't particularly consistent the last I checked, so it would be hard to guarantee support for all exchanges CCXT claims to support, though a good number are compliant.

**Comment by Industrial** [comment]
Is this project still alive?

**Comment by smogili1** [comment]
agree with cal97g, CCXT isn't consistent across different exchanges. Better to do the exchanges you need yourself.
