### ISSUE TITLE
Can we use master branch?

### ISSUE THREAD

**Issue by bartosh** [zipline-live/zipline#13]
Hi,

I'd propose to use 'master' branch instead of 'live' for the following reasons:
- it's default git branch and git checks it out when you do fresh repository clone
- we don't need to change branch in README.rst and .travis.yml 
- we reducing possibility to conflict with upstream

Regards,
Ed

**Comment by tibkiss** [comment]
Good idea! I'd suggest that we try to be in sync with upstream. How about rebasing every Sunday?

**Comment by bartosh** [comment]
I'd prefer to have master branch based on the latest release and devel branch based on upstream master. This way our users will be able to run stable code from master. We as a developer will be able to fight with the latest upstream code in devel if we want to :)

**Comment by tibkiss** [comment]
I'm not sure I understand the concept here. If we have two branches (master / devel), then I suppose we'll be pushing to 'devel' first. Once we have a stable product we'll merge to master?

How is it any different than having a 'live' and 'master' (as of today)?

**Comment by bartosh** [comment]
The concept is simple - master branch contains stable code based on the latest zipline release. devel branch(or "live" if you wish - it doesn't matter) contains unstable code and based on zipline master to isolate users from upstream and our own breakages. That's the main idea. We can discuss details further if main idea is acceptable.

**Comment by bartosh** [comment]
Just found this detailed explanations of the similar model: http://nvie.com/posts/a-successful-git-branching-model/

**Comment by tibkiss** [comment]
Thanks for the explanation. What's still unclear to me is where are you planning to post the Live related PRs to: devel/live, master or both?

My point being is that our code is much more in alpha state at the moment. Using any devel version of zipline might be more stable than our trial on get live trading working.

**Comment by bartosh** [comment]
This makes sense to me. Let's keep using live until we have working and stable code.

**Comment by tibkiss** [comment]
Done with https://github.com/zipline-live/zipline/pull/27
