### ISSUE TITLE
live is broken?

### ISSUE THREAD

**Issue by bartosh** [zipline-live/zipline#16]
Hi,

PR 15 fails tests with below error. I suspect that this is caused by changes in 'live'. How come they've got merged if they're failing tests?

======================================================================
ERROR: test_panel_data_0_daily (tests.test_algorithm.TestPanelData)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/miniconda/envs/testenv/lib/python2.7/site-packages/nose_parameterized/parameterized.py", line 365, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File "/home/travis/build/zipline-live/zipline/tests/test_algorithm.py", line 4750, in test_panel_data
    data=panel
  File "/home/travis/build/zipline-live/zipline/zipline/utils/run_algo.py", line 384, in run_algorithm
    environ=environ,
TypeError: _run() takes exactly 20 arguments (18 given)

Regards,
Ed

**Comment by tibkiss** [comment]
Thanks for reporting, I have a fix for these issues. I'm just waiting for https://github.com/zipline-live/zipline/pull/12 to get merged as the fix will likely to be conflicting with that PR.

**Comment by bartosh** [comment]
#12 needs to be rebased on top of benchmark fix, I'm afraid. I think it's better to merge the fix, then fix tests in live branch. After that we can get back to this PR.

**Comment by tibkiss** [comment]
Create a PR which fixes the testcases: https://github.com/zipline-live/zipline/pull/17

**Comment by bartosh** [comment]
I thought it's not possible to fix travis and AppVeyor builds without merging PR #15. Are you going to merge it anytime soon?

**Comment by tibkiss** [comment]
I misunderstood your comment: thought you are suggesting that we shall merge the testcase fix first. Re-reading it clarified the intent.

I cannot merge #12 as it is in conflict state. Please resolve the conflict then I'll merge it ASAP.

**Comment by bartosh** [comment]
Sorry for this confusion. Correct order of merging is: #15, #17, #12.  I'll rebase #12 as soon as both tests suites are 'green'.

**Comment by tibkiss** [comment]
Thanks for the clarification. Merged #15, will fix #17 soon, then we can proceed with #12.

**Comment by tibkiss** [comment]
I believe this could be closed now.
