### ISSUE TITLE
Add command line option to list the available brokers

### ISSUE THREAD

**Issue by tibkiss** [zipline-live/zipline#48]
As of today one needs to know the supported broker and it's respective name.
It would be helpful to add a command line argument which would list the available brokers (e.g. --broker-list).

**Comment by Scapogo** [comment]
Hello,
 I can do that but what is your preferred level where this command should work? It should be zipline --broker-list or zipline run --broker-list?

**Comment by tibkiss** [comment]
Thanks for your interest in this task.
I'd suggest to add it to run, it is bound to algo execution which is reachable through run.

**Comment by tibkiss** [comment]
Thanks for the smooth delivery Jan!
