### ISSUE TITLE
Broker Not Found Error

### ISSUE THREAD

**Issue by eudisd** [zipline-live/zipline#52]
Dear Zipline Maintainers,
From the zipline-live.io tutorial:

Installation of zipline-live works fine.  Downloading the quandl bundle works fine as well.  However, when I try to run the zipline-live demo program, with the following command:

```
zipline run -f ~/zipline-algos/demo.py --broker ib --broker-uri localhost:7496:1232 --bundle quantopian-quandl  --data-frequency minute
```

I get an error.

# Environment

* Operating System: `Darwin MacBook-Pro.local 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64 i386 MacBookPro13,3 Darwin`
* Python Version: `Python 2.7.10`
* Python Bitness: `64`
* How did you install Zipline: `pip`
* Python packages:
```bash
alembic==0.9.5
bcolz==0.12.1
Bottleneck==1.2.1
certifi==2017.7.27.1
chardet==3.0.4
click==6.7
contextlib2==0.5.5
cyordereddict==1.0.0
Cython==0.26
decorator==4.1.2
empyrical==0.3.2
idna==2.6
intervaltree==2.1.0
Logbook==1.1.0
lru-dict==1.1.6
Mako==1.0.7
MarkupSafe==1.0
multipledispatch==0.4.9
networkx==1.11
numexpr==2.6.2
numpy==1.13.1
pandas==0.18.1
pandas-datareader==0.5.0
patsy==0.4.1
python-dateutil==2.6.1
python-editor==1.0.3
pytz==2017.2
requests==2.18.4
requests-file==1.4.2
requests-ftp==0.3.1
scipy==0.19.1
six==1.10.0
sortedcontainers==1.5.7
SQLAlchemy==1.1.13
statsmodels==0.8.0
tables==3.4.2
TBB==0.1
toolz==0.8.2
urllib3==1.22
zipline-live==0.1.0.0
```

Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue
```bash
[box@MacBook-Pro] ~
❯ zipline run -f ~/zipline-algos/demo.py --broker ib --broker-uri localhost:7496:1232 --bundle quantopian-quandl  --data-frequency minute

Usage: zipline run [OPTIONS]

Error: unsupported broker: can't import module zipline.gens.brokers.ib_broker
```

* What did you expect to happen?
I expected to run zipline-live correctly.
* What happened instead?
The error above occured

Here is how you can reproduce this issue on your machine:

## Reproduction Steps

1.
```bash
virtualenv ~
source ~/venv-zipline-live/bin/activate
pip install zipline-live[ib]
```
2. `zipline ingest -b quantopian-quandl`
3.
```bash
zipline run -f ~/zipline-algos/demo.py --broker ib --broker-uri localhost:7496:1232 --bundle quantopian-quandl  --data-frequency minute
```
...

## What steps have you taken to resolve this already?
N/A
...

# Anything else?

N/A

**Comment by tibkiss** [comment]
Thanks for the detailed report.

For some reason IbPy2 is not installed in your environment.
`pip install zipline-live[ib]` should ensure that ibpy2 as a dependency is installed.

Please make a try to run `pip install IbPy2==0.8.0` inside your virtualenvironment.

Unfortunately the error message is not helpful here (unsupported broker), we have an issue
opened against that: https://github.com/zipline-live/zipline/issues/47

**Comment by eudisd** [comment]
That did it!  Thanks @tibkiss, this solved my problem.  I think the problem this issue should address now is why IbPy2 is not installed when zipline-live is installed?

**Comment by tibkiss** [comment]
For others `pip install zipline-live[ib]` brings in IbPy2 as dependency, I'm not sure why did not bring it in for you. Could you please check and make sure you run that command?

In some shells (such as zsh) the zipline-live[ib] part should be quoted to properly pass the profile inside the braces: `pip install "zipline-live[ib]"`

**Comment by eudisd** [comment]
yup thats it i believe.  i use zsh which caused the issue.  thanks for the help, closing this issue
