### ISSUE TITLE
Problem with data.current()

### ISSUE THREAD

**Issue by ItachiUchiha91** [zipline-live/zipline#97]
Dear Zipline Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

* Operating System: Arch Linux 4.15.6-1-ARCH
* Python Version: Python 3.6.4
* Python Bitness: 64
* How did you install Zipline: pip
* Python packages:
aiodns==1.1.1
aiohttp==3.0.1
alembic==0.9.8
appdirs==1.4.3
async-timeout==2.0.0
attrdict==2.0.0
attrs==17.4.0
bcolz==0.12.1
beautifulsoup4==4.6.0
bleach==2.1.2
boto3==1.5.31
botocore==1.8.45
Bottleneck==1.2.1
bs4==0.0.1
cchardet==2.1.1
ccxt==1.10.1138
certifi==2018.1.18
chardet==3.0.4
chrome-gnome-shell==0.0.0
click==6.7
click-plugins==1.0.3
cligj==0.4.0
contextlib2==0.5.5
cycler==0.10.0
cyordereddict==1.0.0
Cython==0.27.3
cytoolz==0.9.0
decorator==4.2.1
descartes==1.1.0
docutils==0.14
empyrical==0.4.0
enigma-catalyst==0.5.3
entrypoints==0.2.3
enum34==1.1.6
eth-abi==1.0.0b0
eth-account==0.1.0a2
eth-keyfile==0.5.1
eth-keys==0.2.0b1
eth-rlp==0.1.0a2
eth-utils==1.0.0b1
Fiona==1.7.11
geopandas==0.3.0
googlemaps==2.5.1
hexbytes==0.1.0b0
html5lib==1.0.1
IbPy2==0.8.0
idna==2.6
idna-ssl==1.0.0
intervaltree==2.1.0
ipykernel==4.6.1
ipython==6.2.1
ipython-autotime==0.1
ipython-genutils==0.1.0
ipywidgets==6.0.0
jedi==0.11.1
Jinja2==2.10
jmespath==0.9.3
joblib==0.11
jsonschema==2.6.0
jupyter-client==5.2.2
jupyter-console==5.2.0
jupyter-core==4.4.0
Keras==2.1.2
Logbook==1.2.1
lru-dict==1.1.6
lxml==4.1.1
Mako==1.0.7
Markdown==2.6.10
MarkupSafe==1.0
matplotlib==2.1.1
mistune==0.8.1
multidict==4.1.0
multipledispatch==0.4.9
munch==2.2.0
nbconvert==5.3.1
nbformat==4.4.0
networkx==2.1
notebook==5.3.0
numexpr==2.6.4
numpy==1.13.3
packaging==16.8
pandas==0.18.1
pandas-datareader==0.6.0
pandocfilters==1.4.2
parso==0.1.1
patsy==0.5.0
pexpect==4.3.1
pickleshare==0.7.4
prompt-toolkit==1.0.15
protobuf==3.5.1
ptyprocess==0.5.2
pycairo==1.16.2
pycares==2.3.0
pycryptodome==3.4.11
pygame==1.9.3
Pygments==2.2.0
pygobject==3.26.1
pyparsing==2.2.0
pyproj==1.9.5.1
pysha3==1.0.2
python-dateutil==2.6.1
python-editor==1.0.3
pytz==2017.3
PyYAML==3.12
pyzmq==16.0.3
redo==1.6
requests==2.18.4
requests-file==1.4.3
requests-ftp==0.3.1
requests-toolbelt==0.8.0
rlp==0.6.0
s3transfer==0.1.13
sas7bdat==2.0.7
scikit-learn==0.19.1
scipy==1.0.0
seaborn==0.8.1
Send2Trash==1.5.0
Shapely==1.6.3
simplegeneric==0.8.1
six==1.11.0
sklearn==0.0
sortedcontainers==1.5.9
SQLAlchemy==1.2.3
statsmodels==0.8.0
TA-Lib==0.4.16
tables==3.4.2
team==1.0
tensorflow==1.4.1
tensorflow-tensorboard==0.4.0rc3
terminado==0.8.1
testpath==0.3.1
toolz==0.9.0
tornado==4.5.3
traitlets==4.3.2
urllib3==1.22
virtualenv==15.1.0
wcwidth==0.1.7
web3==4.0.0b9
webencodings==0.5.1
Werkzeug==0.13
widgetsnbextension==2.0.0
wrapt==1.10.11
xgboost==0.7.post3
yarl==1.1.0
zipline==1.1.1
zipline-live==1.1.0.4

Now that you know a little about me, let me tell you about the issue I am
having:

I fellow the tutorial http://www.zipline-live.io/tutorial with a IB demo account, but when I run the command:
`zipline run -f ~/zipline-algos/demo.py --state-file ~/zipline-algos/demo.state --realtime-bar-target ~/zipline-algos/realtime-bars/ --broker ib --broker-uri localhost:7496:1232 --bundle quantopian-quandl --data-frequency minute`
I receive the message:

> "Requested market data is not subscribed. Delayed market data is not enabled"

So I am not able to see the AAPL prices.
If it can help, I am able to sell and buy stocks.

Finally I also tried to replicate the procedure on a Ubuntu virtual machine, but I get the same error.

Thanks

**Comment by VitalyErmilov** [comment]
I was having the same message when I tried to run demo.py without data subscription. I did not try to use delayed data, I solved the problem by subscribing to real time date in ib account management section.

**Comment by ItachiUchiha91** [comment]
Thanks for the answer. So the demo account is not sufficient

**Comment by peterfabakker** [comment]
correct demo account works slightly different
